steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/speak_sure:$COMMIT_SHA', '--no-cache', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/speak_sure:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'speak-sure'
  - '--image'
  - 'gcr.io/$PROJECT_ID/speak_sure:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  env:
  - 'DB_HOST=$_DB_HOST'
  - 'DB_PORT=$_DB_PORT'
  - 'DB_USERNAME=$_DB_USERNAME'
  - 'DB_PASSWORD=$_DB_PASSWORD'
  - 'DB_NAME=$_DB_NAME'
  - 'JWT_SECRET=$_JWT_SECRET'
  - 'JWT_EXP=$_JWT_EXP'
images:
- 'gcr.io/$PROJECT_ID/speak_sure:$COMMIT_SHA'